// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVrmx8GBKsul2MEmEgf4vXq8RZy00J4d8',
    appId: '1:998394170084:web:a72848c6a4ce7d74493af1',
    messagingSenderId: '998394170084',
    projectId: 'finderrec',
    authDomain: 'finderrec.firebaseapp.com',
    storageBucket: 'finderrec.firebasestorage.app',
    measurementId: 'G-EXXHZTG0K6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4A77PgyQvAd51eWqFK221TfXiF5NJnUo',
    appId: '1:998394170084:android:8ad2e328326a0cb5493af1',
    messagingSenderId: '998394170084',
    projectId: 'finderrec',
    storageBucket: 'finderrec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBouIp1MSPCNEnOkY4nDwPFKpGNV4CMMR8',
    appId: '1:998394170084:ios:8ff13f7ceb995524493af1',
    messagingSenderId: '998394170084',
    projectId: 'finderrec',
    storageBucket: 'finderrec.firebasestorage.app',
    iosBundleId: 'com.example.finderrec',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBouIp1MSPCNEnOkY4nDwPFKpGNV4CMMR8',
    appId: '1:998394170084:ios:8ff13f7ceb995524493af1',
    messagingSenderId: '998394170084',
    projectId: 'finderrec',
    storageBucket: 'finderrec.firebasestorage.app',
    iosBundleId: 'com.example.finderrec',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVrmx8GBKsul2MEmEgf4vXq8RZy00J4d8',
    appId: '1:998394170084:web:2e60805a70d8b774493af1',
    messagingSenderId: '998394170084',
    projectId: 'finderrec',
    authDomain: 'finderrec.firebaseapp.com',
    storageBucket: 'finderrec.firebasestorage.app',
    measurementId: 'G-LLRFSBJT82',
  );
}
